name: 'uploading-testing-ftp'
author: 'Allan Wanderley <awallan259@gmail.com>'
description: 'Sample description'
inputs:
  host:
    description: 'FTP host'
    required: true
  user:
    description: 'FTP user'
    required: true
  password:
    description: 'FTP password'
    required: true
  forceSsl:
    description: 'Force SSL encryption'
    required: false
    default: 'false'
  localDir:
    description: 'Local directory'
    required: false
    default: '.'
  remoteDir:
    description: 'Remote directory'
    required: false
    default: '.'
  options:
    description: 'Additional mirror command options'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: 'red'
  icon: 'upload-cloud'
